sudo: required
language: node_js
node_js:
  - "8"
addons:
  apt:
    sources:
      - google-chrome
    packages:
      - google-chrome-stable
cache:
  directories:
  - node_modules
install:
  - npm install -g truffle
  - npm install -g ganache-cli
  - npm install
script:
  #- npm run lint
  - stage: test
  - npm run ganache
  - sleep 5
  - truffle migrate --network development
  - npm run test/truffle 
  - npm run unit
  - npm run e2e
  - npm run stop
  - stage: solidity-docs
  - sudo add-apt-repository -y ppa:ethereum/ethereum
  - sudo apt-get update
  - sudo apt-get -y install solc
  - solidity-docgen . contracts docs
after_script:
  - npm run coverage && cat coverage/lcov.info | coveralls