sudo: required
language: node_js
node_js:
  - "8"
cache:
  directories:
  - node_modules
install:
  - npm install -g truffle
  - npm i -g ganache-cli
  - npm i -g solidity-coverage
  - npm install
  - pip2 install slither-analyzer
  - npm install -g python@2.7
script:
  #- npm run lint
  - bash test.sh
  - slither 
after_script:
#  - npx solidity-coverage