language: node_js
node_js:
  - "8"
cache:
  directories:
  - node_modules
install:
  - npm install -g truffle
  - npm i -g ganache-cli
  - npm i -g solidity-coverage
  - npm install
  - npm install -g solgraph
  - npm install -g surya
 
script:
  - bash test.sh
  - surya describe contracts/*.sol
  - solgraph contracts/*.sol  

after_script:
#  - npx solidity-coverage

language: python
python:
    - 3.6
install:
    - pip install slither-analyzer
script:
 - slither .