sudo: required
language: node_js
node_js:
  - "8"
cache:
  directories:
  - node_modules
install:
  - npm install -g truffle
  - npm i -g ganache-cli
  - npm i -g solidity-coverage
  - npm install
script:
  #- npm run lint
  - bash test.sh
after_script:
#  - npx solidity-coverage