sudo: required
language: node_js
node_js:
  - "8"
cache:
  directories:
  - node_modules
install:
  - npm install -g truffle
  - npm i -g ganache-cli
  - npm i -g solidity-coverage
  - npm install
  - npm install -g surya
  - npm install -g python3.6
  - python3 -V
  - pip3 install slither-analyzer
script:
  #- npm run lint
  - bash test.sh
  - surya describe contracts/*.sol  
after_script:
  - npx solidity-coverage