version: 2
jobs:
  build:
    docker:
      - image: circleci/node:10
      - image: circleci/python:3.6.4 

        environment:
          PIPENV_VENV_IN_PROJECT: true
    working_directory: ~/repo

    steps:
      - checkout

      - run: npm install 
      - run: sudo npm i -g ganache-cli
      - run: sudo npm i -g truffle@4.1.14
      - run: pip install slither-analyzer  

      - save_cache:
          paths:
            - node_modules
          key: v1-dependencies-{{ checksum "package.json" }}

      - run: bash test.sh




