version: 2
jobs:
  build:
    docker:
      - image: circleci/node:10

    working_directory: ~/repo

    steps:
      - checkout

      - run: npm install 
      - run: sudo npm i -g ganache-cli
      - run: sudo npm i -g truffle@4.1.14 
      - run: sudo npm install surya
      - run: sudo npm i -g solidity-coverage

      - save_cache:
          paths:
            - node_modules
          key: v1-dependencies-{{ checksum "package.json" }}

      - run: bash test.sh
      - run: surya describe contracts/*.sol
#      - run: solgraph contracts/*.sol
      - run: npx solidity-coverage



